"""Backend-authoritative Session subsystem public interface."""

from backend.app.algorithms.session.compatibility import SESSION_SIGNAL_NAMES, session_classification_to_layer_result
from backend.app.algorithms.session.calendar import SessionClock, exchange_session_bounds, resolve_session_clock
from backend.app.algorithms.session.baselines import (
    SessionBaselineArtifact,
    baseline_for_decision,
    build_session_baseline_artifact,
    select_session_baseline_artifact,
)
from backend.app.algorithms.session.backtest import (
    SESSION_RUNTIME_PARITY_VERSION,
    SessionBacktestEngine,
    SessionBacktestExecutionConfig,
    SessionBacktestExecutionResult,
    SessionRuntimeDecisionSnapshot,
    SessionRuntimeParityResult,
    compare_session_runtime_parity,
    run_session_backtest,
    run_session_event_stream,
)
from backend.app.algorithms.session.classifier import SessionAxisClassification, classify_session_axes
from backend.app.algorithms.session.config import DEFAULT_SESSION_CONFIG, SESSION_CONFIG_VERSION, SessionConfig
from backend.app.algorithms.session.diagnostics import SESSION_DIAGNOSTICS_VERSION, SessionOperationalMetrics, build_session_operational_metrics
from backend.app.algorithms.session.execution import (
    SESSION_EXECUTION_BOUNDARY_VERSION,
    SESSION_GLOBAL_IMMUTABILITY_CHECKS,
    SessionCandidateDecision,
    SessionExecutionLatencyRecord,
    SessionOrderGateDecision,
    build_session_candidate_decision,
    evaluate_session_candidate_order_gate,
    session_expected_net_edge,
)
from backend.app.algorithms.session.models import (
    SESSION_ALGORITHM_ID,
    SESSION_CLASSIFIER_VERSION,
    SESSION_FEATURE_SCHEMA_VERSION,
    DataQualityState,
    EventRiskState,
    LiquidityState,
    SessionBehavior,
    SessionClassification,
    SessionPhase,
    VolatilityState,
)
from backend.app.algorithms.session.profile import SessionProfile, baseline_session_profile
from backend.app.algorithms.session.research import (
    SESSION_RESEARCH_REPORT_VERSION,
    SessionCalibrationCandidate,
    SessionCalibrationReport,
    SessionCalibrationRunnerConfig,
    SessionCalibrationStressResult,
    SessionPartitionPlan,
    run_session_characterization_calibration,
    save_immutable_session_report,
)
from backend.app.algorithms.session.rollout import (
    SESSION_ROLLBACK_STATE_KEY,
    SESSION_ROLLOUT_NAMESPACE,
    SESSION_ROLLOUT_STAGES,
    SESSION_ROLLOUT_STATE_KEY,
    SESSION_ROLLOUT_VERSION,
    SessionHealthStatus,
    SessionOrderAuthority,
    SessionPromotionEvidence,
    SessionRolloutControl,
    SessionRolloutFlags,
    SessionRolloutPermission,
    SessionRolloutStage,
    SessionRolloutStageStatus,
    SessionRolloutValidation,
    build_session_promotion_evidence,
    evaluate_session_rollout_control,
    evaluate_session_rollout_stage,
    initial_session_rollout_validation,
    order_authority_for_stage,
    record_approved_session_rollout_version,
    rollback_session_rollout,
    session_rollout_feature_flags,
    session_rollout_status,
    validation_from_evidence,
)
from backend.app.algorithms.session.persistence import (
    SESSION_DECISION_RECORD_SCHEMA_VERSION,
    SESSION_PERSISTENCE_VERSION,
    BufferedSessionDecisionWriter,
    SessionDecisionJsonlStore,
    SessionDecisionPersistenceRecord,
    SessionPersistenceEnqueueResult,
    SessionPersistenceFlushResult,
    build_session_decision_record,
)
from backend.app.algorithms.session.router import resolve_session_profile, session_route_permissions
from backend.app.algorithms.session.liquidity import analyze_session_liquidity
from backend.app.algorithms.session.opening_range import analyze_opening_ranges
from backend.app.algorithms.session.runtime import EventDrivenSessionRuntime, classify_session, legacy_failed_breakouts, legacy_liquidity_stress_signal, legacy_volume_pace
from backend.app.algorithms.session.state import (
    ACCEPTED_SESSION_EVENT_TYPES,
    FINALIZED_ONE_MINUTE_BAR,
    MARKET_STATUS_CALENDAR_UPDATE,
    QUOTE_NBBO_UPDATE,
    REPLAY_RESET,
    SCHEDULED_EVENT_RISK_UPDATE,
    SESSION_RESET,
)
from backend.app.algorithms.session.structure import analyze_session_structure
from backend.app.algorithms.session.transition import SessionTransitionManager, SessionTransitionRecord, SessionTransitionState
from backend.app.algorithms.session.volatility import analyze_session_volatility
from backend.app.algorithms.session.volume import analyze_session_participation
from backend.app.algorithms.session.vwap import analyze_vwap, vwap_at

__all__ = [
    "DEFAULT_SESSION_CONFIG",
    "SESSION_ALGORITHM_ID",
    "SESSION_CLASSIFIER_VERSION",
    "SESSION_CONFIG_VERSION",
    "SESSION_DECISION_RECORD_SCHEMA_VERSION",
    "SESSION_DIAGNOSTICS_VERSION",
    "SESSION_EXECUTION_BOUNDARY_VERSION",
    "SESSION_FEATURE_SCHEMA_VERSION",
    "SESSION_GLOBAL_IMMUTABILITY_CHECKS",
    "SESSION_PERSISTENCE_VERSION",
    "SESSION_RUNTIME_PARITY_VERSION",
    "SESSION_RESEARCH_REPORT_VERSION",
    "SESSION_ROLLBACK_STATE_KEY",
    "SESSION_ROLLOUT_NAMESPACE",
    "SESSION_ROLLOUT_STAGES",
    "SESSION_ROLLOUT_STATE_KEY",
    "SESSION_ROLLOUT_VERSION",
    "SESSION_SIGNAL_NAMES",
    "ACCEPTED_SESSION_EVENT_TYPES",
    "BufferedSessionDecisionWriter",
    "DataQualityState",
    "EventRiskState",
    "EventDrivenSessionRuntime",
    "FINALIZED_ONE_MINUTE_BAR",
    "LiquidityState",
    "MARKET_STATUS_CALENDAR_UPDATE",
    "QUOTE_NBBO_UPDATE",
    "REPLAY_RESET",
    "SCHEDULED_EVENT_RISK_UPDATE",
    "SESSION_RESET",
    "SessionBehavior",
    "SessionAxisClassification",
    "SessionBaselineArtifact",
    "SessionBacktestEngine",
    "SessionBacktestExecutionConfig",
    "SessionBacktestExecutionResult",
    "SessionCandidateDecision",
    "SessionCalibrationCandidate",
    "SessionCalibrationReport",
    "SessionCalibrationRunnerConfig",
    "SessionCalibrationStressResult",
    "SessionClassification",
    "SessionClock",
    "SessionConfig",
    "SessionDecisionJsonlStore",
    "SessionDecisionPersistenceRecord",
    "SessionExecutionLatencyRecord",
    "SessionHealthStatus",
    "SessionOperationalMetrics",
    "SessionOrderAuthority",
    "SessionOrderGateDecision",
    "SessionPersistenceEnqueueResult",
    "SessionPersistenceFlushResult",
    "SessionPartitionPlan",
    "SessionPhase",
    "SessionProfile",
    "SessionPromotionEvidence",
    "SessionRolloutControl",
    "SessionRolloutFlags",
    "SessionRolloutPermission",
    "SessionRolloutStage",
    "SessionRolloutStageStatus",
    "SessionRolloutValidation",
    "SessionRuntimeDecisionSnapshot",
    "SessionRuntimeParityResult",
    "SessionTransitionManager",
    "SessionTransitionRecord",
    "SessionTransitionState",
    "VolatilityState",
    "classify_session",
    "classify_session_axes",
    "analyze_opening_ranges",
    "analyze_session_participation",
    "analyze_session_liquidity",
    "analyze_session_structure",
    "analyze_session_volatility",
    "analyze_vwap",
    "baseline_for_decision",
    "baseline_session_profile",
    "build_session_baseline_artifact",
    "build_session_candidate_decision",
    "build_session_decision_record",
    "build_session_operational_metrics",
    "build_session_promotion_evidence",
    "compare_session_runtime_parity",
    "exchange_session_bounds",
    "evaluate_session_candidate_order_gate",
    "evaluate_session_rollout_control",
    "evaluate_session_rollout_stage",
    "initial_session_rollout_validation",
    "legacy_failed_breakouts",
    "legacy_liquidity_stress_signal",
    "legacy_volume_pace",
    "order_authority_for_stage",
    "record_approved_session_rollout_version",
    "resolve_session_clock",
    "resolve_session_profile",
    "run_session_backtest",
    "run_session_characterization_calibration",
    "run_session_event_stream",
    "save_immutable_session_report",
    "select_session_baseline_artifact",
    "session_classification_to_layer_result",
    "session_expected_net_edge",
    "session_rollout_feature_flags",
    "session_rollout_status",
    "session_route_permissions",
    "rollback_session_rollout",
    "vwap_at",
    "validation_from_evidence",
]
