import { REGIME_STRATEGY_ALIAS_INVENTORY } from "./aliases.ts";
import { REGIME_CONFIRMATION_MODULE_INVENTORY } from "./confirmation-modules.ts";
import { REGIME_CONTEXT_MODULE_INVENTORY } from "./context-modules.ts";
import { REGIME_DIRECTIONAL_STRATEGY_INVENTORY } from "./directional-strategies.ts";
import { REGIME_SAFETY_GATE_INVENTORY } from "./safety-gates.ts";

export const REGIME_STRATEGY_ROLE_INVENTORY = {
  directional: REGIME_DIRECTIONAL_STRATEGY_INVENTORY,
  confirmation: REGIME_CONFIRMATION_MODULE_INVENTORY,
  regimeContext: REGIME_CONTEXT_MODULE_INVENTORY,
  safetyGate: REGIME_SAFETY_GATE_INVENTORY,
  aliases: REGIME_STRATEGY_ALIAS_INVENTORY,
} as const;

export const REGIME_TOTAL_STRATEGY_DEFINITION_COUNT =
  REGIME_DIRECTIONAL_STRATEGY_INVENTORY.length +
  REGIME_CONFIRMATION_MODULE_INVENTORY.length +
  REGIME_CONTEXT_MODULE_INVENTORY.length +
  REGIME_SAFETY_GATE_INVENTORY.length;

