"""Meta-Strategy-owned out-of-sample forecast generation."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from backend.app.algorithms.meta_strategy.forecast.forecast_contracts import (
    FORECAST_FEATURE_VERSION,
    ForecastFallbackFeature,
    OutOfSampleForecastFeature,
)
from backend.app.algorithms.meta_strategy.forecast.forecast_validation import (
    artifact_training_end,
    artifact_training_start,
    parse_utc,
    reject_full_history_forecast_artifact_for_historical_features,
    row_timestamp,
    validate_oos_fold,
    validate_training_ends_before_prediction,
)


OUTCOME_STOP = -1
OUTCOME_TIMEOUT = 0
OUTCOME_TARGET = 1


def generate_oos_forecast_features(
    rows: list[dict[str, Any]],
    *,
    symbol: str,
    requested_folds: int,
    embargo_minutes: int,
    min_train_rows: int = 20,
    min_validation_rows: int = 5,
) -> list[OutOfSampleForecastFeature]:
    """Generate forecasts only for rows after each fold's training window."""

    sorted_rows = sorted(rows, key=row_timestamp)
    folds = _walk_forward_folds(sorted_rows, requested_folds=requested_folds, embargo_minutes=embargo_minutes)
    features: list[OutOfSampleForecastFeature] = []
    for fold in folds:
        train_rows = fold["trainRows"]
        validation_rows = fold["validationRows"]
        if len(train_rows) < min_train_rows or len(validation_rows) < min_validation_rows:
            continue
        validate_oos_fold(fold)
        base_probabilities = _class_probabilities(train_rows)
        training_start = row_timestamp(train_rows[0])
        training_end = max(row_timestamp(row) for row in train_rows)
        validation_start = row_timestamp(validation_rows[0])
        validation_end = row_timestamp(validation_rows[-1])
        artifact_id = f"{FORECAST_FEATURE_VERSION}:{symbol.upper()}:fold-{fold['fold']}:train-end-{training_end.isoformat()}"
        for row in validation_rows:
            decision_at = row_timestamp(row)
            validate_training_ends_before_prediction(training_window_end_utc=training_end, prediction_time_utc=decision_at)
            probabilities = _row_adjusted_probabilities(row, base_probabilities)
            features.append(
                OutOfSampleForecastFeature(
                    status="out_of_sample",
                    rowId=str(row.get("rowId") or row.get("snapshotId") or row.get("timestamp")),
                    symbol=symbol.upper(),
                    decisionTimestampUtc=decision_at,
                    trainingWindowStartUtc=training_start,
                    trainingWindowEndUtc=training_end,
                    validationWindowStartUtc=validation_start,
                    validationWindowEndUtc=validation_end,
                    fold=int(fold["fold"]),
                    artifactId=artifact_id,
                    probabilityBuySuccess=round(float(probabilities[OUTCOME_TARGET]), 6),
                    probabilitySellSuccess=round(float(probabilities[OUTCOME_STOP]), 6),
                    probabilityTimeout=round(float(probabilities.get(OUTCOME_TIMEOUT, 0.0)), 6),
                    reasonCodes=("forecast_feature.out_of_sample_validation_prediction",),
                    explanation="Market-forecast feature generated by a model trained only on the outer fold training period.",
                )
            )
    return features


def _walk_forward_folds(rows: list[dict[str, Any]], *, requested_folds: int, embargo_minutes: int) -> list[dict[str, Any]]:
    if requested_folds <= 0 or not rows:
        return []
    fold_count = min(requested_folds, max(1, len(rows) - 1))
    fold_width = max(1, len(rows) // (fold_count + 1))
    folds: list[dict[str, Any]] = []
    for fold_number in range(1, fold_count + 1):
        validation_start_index = min(len(rows) - 1, fold_width * fold_number)
        validation_end_index = len(rows) if fold_number == fold_count else min(len(rows), validation_start_index + fold_width)
        validation_rows = rows[validation_start_index:validation_end_index]
        if not validation_rows:
            continue
        validation_start = row_timestamp(validation_rows[0])
        train_rows = [
            row
            for row in rows[:validation_start_index]
            if (validation_start - row_timestamp(row)).total_seconds() / 60.0 > embargo_minutes
        ]
        folds.append({"fold": fold_number, "trainRows": train_rows, "validationRows": validation_rows})
    return folds


def _class_probabilities(train_rows: list[dict[str, Any]]) -> dict[int, float]:
    counts = {OUTCOME_TARGET: 1.0, OUTCOME_STOP: 1.0, OUTCOME_TIMEOUT: 1.0}
    for row in train_rows:
        target = int(row.get("target", OUTCOME_TIMEOUT))
        if target in counts:
            counts[target] += 1.0
    total = sum(counts.values())
    return {outcome: count / total for outcome, count in counts.items()}


def _row_adjusted_probabilities(row: dict[str, Any], base_probabilities: dict[int, float]) -> dict[int, float]:
    features = row.get("features") or {}
    trend = _bounded_float(features.get("trend"), default=0.5)
    momentum = _bounded_float(features.get("momentum"), default=0.5)
    edge = ((trend + momentum) / 2.0) - 0.5
    target = max(0.001, base_probabilities[OUTCOME_TARGET] + (edge * 0.08))
    stop = max(0.001, base_probabilities[OUTCOME_STOP] - (edge * 0.08))
    timeout = max(0.001, base_probabilities[OUTCOME_TIMEOUT])
    total = target + stop + timeout
    return {
        OUTCOME_TARGET: target / total,
        OUTCOME_STOP: stop / total,
        OUTCOME_TIMEOUT: timeout / total,
    }


def _bounded_float(value: Any, *, default: float) -> float:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return default
    return min(1.0, max(0.0, parsed))


def missing_forecast_feature() -> ForecastFallbackFeature:
    return ForecastFallbackFeature()


def select_live_forecast_feature(
    *,
    decision_timestamp_utc: datetime,
    approved_artifacts: list[dict[str, Any]],
    symbol: str,
) -> OutOfSampleForecastFeature | ForecastFallbackFeature:
    decision_at = parse_utc(decision_timestamp_utc.isoformat())
    candidates: list[tuple[datetime, dict[str, Any]]] = []
    for artifact in approved_artifacts:
        if str(artifact.get("symbol") or "").upper() != symbol.upper():
            continue
        if artifact.get("approved") is not True:
            continue
        training_end = artifact_training_end(artifact)
        if training_end and training_end < decision_at:
            candidates.append((training_end, artifact))
    if not candidates:
        return missing_forecast_feature()
    training_end, artifact = max(candidates, key=lambda item: item[0])
    return OutOfSampleForecastFeature(
        status="live_approved_artifact",
        rowId=f"live:{symbol.upper()}:{decision_at.isoformat()}",
        symbol=symbol.upper(),
        decisionTimestampUtc=decision_at,
        trainingWindowStartUtc=artifact_training_start(artifact) or training_end,
        trainingWindowEndUtc=training_end,
        artifactId=str(artifact.get("artifactId") or artifact.get("modelVersion") or artifact.get("version") or "approved_forecast_artifact"),
        modelKind=str(artifact.get("modelKind") or "approved_forecast_artifact"),
        probabilityBuySuccess=0.0,
        probabilitySellSuccess=0.0,
        probabilityTimeout=0.0,
        reasonCodes=("forecast_feature.live_approved_artifact_available",),
        explanation="Live inference may use this approved forecast artifact because its training end precedes the decision timestamp.",
    )


__all__ = [
    "FORECAST_FEATURE_VERSION",
    "ForecastFallbackFeature",
    "OutOfSampleForecastFeature",
    "generate_oos_forecast_features",
    "missing_forecast_feature",
    "reject_full_history_forecast_artifact_for_historical_features",
    "select_live_forecast_feature",
    "validate_oos_fold",
]
